title: 极客派
author: 赵军旺
email: zhjwpku@gmail.com
d1: Trying to be an excellent programmer.
d2:  Keep looking, don't settle.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://yourdomain.com" # the base hostname & protocol for your site
github_username:  zhjwpku

# Build settings
markdown: kramdown

url: http://blog.geekpi.cc

timezone: Asia/Shanghai

years:
- "2016"

#main_menu:
#- label: Home
#  url: /index.html
#- label: Ceph
#  url: /ceph.html
#- label: Docker
#  url: /docker.html
#- label: OpenStack
#  url: /opensstack.html
#- label: Tags
#  url: /tags.html
